In [1]:
import numpy as np
import pandas as pd
arr1 = np.array([1,2,3,4])
arr1.dtype
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr3)
df = pd.DataFrame()
x = df.values
type(x)
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
np.empty(5) # one-dimensional array of five elements for which memory is allocated but not initialized
np.zeros((10, 7)) # array of size 10x7 filled with zeros 
np.ones((3,3,3)) # 3x3x3 array filled with units
np.eye(3) # identity matrix (elements of the main diagonal are 1, the rest are 0) of size 3x3
np.full((3, 5), 3.14)  # 3x5 array filled with number 3.14
np.arange(0, 21, 7)  # one-dimensional array filled with numbers in the range from 0 to 20 in increments of 7
np.linspace(0, 1, 5)  # an array of five numbers evenly distributed between 0 and 1 inclusive
np.random.randint(0, 10, (3, 3))  # 3x3 array filled with random numbers from the range from 0 to 10
Z = append([[1 for _ in range(0,len(Z))]], Z.T,0).T

In [ ]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])

my_array[:,3]
my_array.shape

In [41]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
x=[]

for i in big_secret:
    x=big_secret[:, 46:52]
    
sum_main = x[0,0]*x[1,1]*x[2,2]*x[3,3]*x[4,4]
sum_main

341505315559.2347

In [25]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line], dtype = float)

for i in enumerate(big_secret):
    if i[0]%2==0:
        np.put(big_secret,[i for i in range(0,255) if i%2==0], [-1])
    else:
        np.put(big_secret,[i for i in range(0,255) if i%2==1], [1])
         
x=[]
for i in enumerate(big_secret):
    x=big_secret[:, 46:52]

sum_main = x[0,0]*x[1,1]*x[2,2]*x[3,3]*x[4,4]
sum_main


-1.0

In [5]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_slice = my_array[1:3, 2:4]
my_slice
my_slice[:] = 0
my_array

array([[64, 17,  0,  0, 73, 10]])

In [ ]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Sum: {} \ nDifference: {} \ nProduction: {} \ nPrivate: {} \ nMultiplication by a number: {} '.format(result1, result2, result3, result4, result5))

In [ ]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

my_array = np.random.randint(0, 10, (3,4))
my_array[my_array<5]

mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

my_array = np.random.randint(0, 10, (4, 6))

np.sort(my_array, axis=1)

np.sort(my_array, axis=0)

In [ ]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

# sum(great_secret[great_secret>50])

s = np.sort(great_secret, axis=0 )
sum(s[99])

In [2]:
import numpy as np
import pandas as pd

students= np.array([[1,2,3,4,5,6,7,8,9,10],[135,160,163,147,138,149,136,154,137,165],[34,43,40,44,41,54,39,48,35,60],[4,5,4.3,5,4.7,3.9,4.2,4.9,3.7,4.6]  ]).T

mean = np.mean(students[:,-1])

median = np.median(students[:,-2])

corr = np.corrcoef(students[:,2], students[:,3])

std = np.std(students[:,3])

dis = np.var(students[:,2])


60.36

In [3]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
# my_array[1:4, 1:4]
my_sin = np.sin(my_array)
# np.sum(my_array)
my_sin[1:4, 1:4] = 1.0
# np.sum(my_sin)

a = my_sin[:, 0:4]

b = a.reshape((10,2))

np.sum(b[:, 0])

2.4057172058139544

In [4]:
bigdata = np.array([i**2 for i in range(100, 1000) if i%2==1 ])
b = [v for k,v in enumerate(bigdata) if not k%2]
c = [v for k,v in enumerate(bigdata) if k%2==1]

np.median(bigdata)
np.std(bigdata)
np.corrcoef(b, c)

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])